In [197]:
import numpy as np
import pandas as pd

1. How likely is it that you roll doubles when rolling two dice?

In [141]:
n_trials = nrows = 100_000
n_dice = ncols = 2

rolls = pd.DataFrame(np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols))
rolls

rolls['doubles'] = False
rolls

for row in range(0,len(rolls)):
    rolls.loc[row, 'doubles'] = rolls.iloc[row, 0] == rolls.iloc[row, 1]
    
rolls['doubles'].mean()

0.16775

In [142]:
(rolls[0]-rolls[1] == 0).sum()/len(rolls) 

0.16775

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [143]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = pd.DataFrame(np.random.choice([0,1], n_trials * n_coins).reshape(nrows,ncols))

flips.head()

0  1  2  3  4  5  6  7
0  1  0  0  1  0  0  0  1
1  0  1  1  1  0  1  1  1
2  0  0  0  0  0  0  0  0
3  1  1  1  1  0  1  1  1
4  0  1  1  0  0  0  0  1

In [144]:
# (flips.sum(axis =1) == 3).mean()

sums_by_trial = flips.sum(axis=1)

heads_by_three = sums_by_trial == 3

heads_by_three.mean()

0.2185

In [145]:
#(flips.sum(axis =1) > 3).mean()
greater_heads = sums_by_trial > 3

greater_heads.mean()

0.636

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [148]:
n_trials = nrows = 10000
n_billboard = ncols = 2
p_ds = .25


In [149]:
data = pd.DataFrame(np.random.random((nrows, ncols)))
data.head()

0         1
0  0.717854  0.343564
1  0.186244  0.282213
2  0.800451  0.917330
3  0.017182  0.195426
4  0.838467  0.207034

In [150]:
((data[0]<= p_ds) & (data[1] <= p_ds)).sum()/len(data) 

0.0622

In [151]:
ds_students = data < p_ds
ds_students

0      1
0     False  False
1      True  False
2     False  False
3      True   True
4     False   True
...     ...    ...
9995  False  False
9996   True  False
9997  False  False
9998   True  False
9999  False  False

[10000 rows x 2 columns]

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [159]:
n_trials = rows = 10_000
n_days = cols = 5

poptarts = pd.DataFrame(np.random.normal(3, 1.5, rows * cols).reshape(rows,cols))

#random.normal(loc=1, scale=2, size=(2, 3))

poptarts.head()

0         1         2         3         4
0  1.502369  3.736398  3.615347  5.098655  1.715776
1  2.511047  1.892626  0.782993  2.280271  3.833275
2 -1.179794  1.661554  0.436062  3.274646  3.037628
3  1.542476  4.689481  3.504141  1.987264  4.540227
4  4.246040  6.943135  4.082074  3.294567  1.430614

In [161]:
poptarts.apply(lambda row: row.values.sum() < 16, axis = 1).mean()

0.6198

5. Compare Heights

 - Men have an average height of 178 cm and standard deviation of 8cm.
 - Women have a mean of 170, sd = 6cm.
 - Since you have means and standard deviations, you can use np.random.normal to generate observations.
 - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [51]:

m_height = pd.DataFrame(np.random.normal(loc=178, scale=8, size=(1,100)))

m_height


0           1           2           3           4           5   \
0  178.262461  179.977582  171.247946  163.587428  168.512546  186.555206   

           6           7           8           9   ...          90  \
0  182.951584  180.258561  167.729191  166.207721  ...  191.311429   

           91          92          93          94          95          96  \
0  185.775899  183.586688  180.944105  187.746127  176.473528  178.051646   

           97          98          99  
0  154.570852  189.928193  179.249744  

[1 rows x 100 columns]

In [52]:
w_height = pd.DataFrame(np.random.normal(loc=170, scale=6, size=(1,100)))

w_height

0           1           2           3           4           5   \
0  173.827488  174.258491  169.456645  163.319913  163.351446  179.483673   

           6           7           8           9   ...          90  \
0  170.971448  178.313745  159.289359  179.892743  ...  167.717813   

           91          92          93          94          95          96  \
0  166.859663  171.788226  167.390299  172.738032  171.672442  174.229453   

           97          98          99  
0  170.150891  165.810409  161.171604  

[1 rows x 100 columns]

In [164]:
p_w_taller = (w_height > m_height).T

p_w_taller.head()

0
0  False
1  False
2  False
3  False
4  False

In [54]:
p_w_taller[0].mean()

0.21

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
 
 - What is the probability that we observe an installation issue within the first 150 students that download anaconda?

 - How likely is it that 450 students all download anaconda without an issue?

In [192]:
n_trial = rows = 100_000
n_students = cols = 50
p_fail = .004


data = np.random.random((rows, cols))
data

array([[0.2888275 , 0.16727208, 0.88313559, ..., 0.94678943, 0.76111884,
        0.40197191],
       [0.99516742, 0.72685651, 0.19327089, ..., 0.17015531, 0.38783172,
        0.79574254],
       [0.13373003, 0.97004232, 0.14515673, ..., 0.38993272, 0.86054413,
        0.27123589],
       ...,
       [0.85859568, 0.7421593 , 0.46037167, ..., 0.84403944, 0.52346319,
        0.68946027],
       [0.90062537, 0.21011981, 0.98295733, ..., 0.00284272, 0.39913564,
        0.96910455],
       [0.54520604, 0.12661815, 0.18415515, ..., 0.60098703, 0.09455356,
        0.86243396]])

In [193]:
students_fail_to_install = data < p_fail

students_fail_to_install

students_fail_to_install.sum(axis=1)

array([0, 0, 0, ..., 0, 1, 0])

In [194]:
(students_fail_to_install.sum(axis=1)).mean()
# for 50 students an 20.03% success
# for 100 students an 39.92%


0.20061

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

 - How likely is it that a food truck will show up sometime this week?

In [78]:
p_food_truck = .70
ndays = ncols = 7

#1000 trials
n_simulated_weekends = nrows = 1_000

data = np.random.random((nrows, ncols))
data

array([[0.24089369, 0.82097064, 0.97762057, ..., 0.41690155, 0.25264476,
        0.54139954],
       [0.75104192, 0.64152705, 0.64827587, ..., 0.95066714, 0.51231305,
        0.13254035],
       [0.22963979, 0.55961836, 0.86010426, ..., 0.77213594, 0.69763327,
        0.19320825],
       ...,
       [0.57383095, 0.69910219, 0.73695422, ..., 0.33995704, 0.65796278,
        0.18316587],
       [0.82995279, 0.09049018, 0.47844837, ..., 0.84387024, 0.87988632,
        0.50837675],
       [0.68807917, 0.39199701, 0.23719645, ..., 0.19643493, 0.39262731,
        0.2653618 ]])

In [86]:
food_truck_park = data > p_food_truck

food_truck_park

array([[False,  True,  True, ..., False, False, False],
       [ True, False, False, ...,  True, False, False],
       [False, False,  True, ...,  True, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [ True, False, False, ...,  True,  True, False],
       [False, False, False, ..., False, False, False]])

In [87]:
food_truck_park.sum(axis=1)

array([3, 2, 2, 2, 3, 3, 1, 3, 0, 0, 4, 4, 1, 3, 4, 1, 2, 2, 2, 1, 3, 1,
       2, 2, 1, 4, 3, 1, 3, 3, 3, 1, 4, 2, 3, 2, 1, 2, 3, 2, 2, 1, 2, 2,
       3, 1, 4, 3, 4, 0, 1, 0, 1, 4, 3, 1, 2, 2, 1, 2, 1, 2, 5, 1, 3, 2,
       3, 2, 2, 2, 4, 3, 3, 1, 0, 2, 3, 2, 4, 1, 1, 4, 2, 3, 4, 4, 3, 1,
       2, 2, 2, 3, 1, 3, 1, 1, 1, 1, 2, 2, 3, 0, 5, 1, 4, 3, 3, 2, 4, 1,
       1, 3, 1, 2, 2, 3, 2, 3, 2, 1, 2, 2, 2, 1, 3, 1, 1, 3, 3, 1, 2, 2,
       1, 3, 4, 4, 1, 0, 1, 3, 0, 1, 2, 4, 1, 2, 2, 4, 3, 2, 1, 1, 2, 2,
       3, 3, 0, 4, 3, 2, 3, 3, 1, 3, 2, 2, 2, 2, 1, 1, 2, 0, 5, 2, 2, 0,
       2, 4, 4, 3, 3, 2, 3, 2, 3, 3, 1, 3, 2, 1, 2, 3, 2, 3, 1, 1, 2, 3,
       2, 2, 2, 1, 4, 1, 4, 3, 1, 4, 2, 3, 2, 4, 4, 2, 3, 3, 2, 2, 1, 2,
       2, 5, 3, 2, 3, 3, 2, 3, 2, 1, 4, 2, 4, 1, 3, 1, 0, 4, 3, 2, 4, 2,
       2, 1, 3, 3, 3, 2, 4, 1, 2, 1, 3, 4, 2, 1, 2, 3, 1, 1, 2, 5, 3, 2,
       2, 2, 3, 1, 2, 0, 1, 2, 2, 1, 1, 4, 3, 4, 2, 0, 1, 3, 2, 0, 2, 3,
       0, 4, 3, 3, 5, 2, 3, 0, 2, 2, 1, 0, 3, 2, 2,

In [88]:
(food_truck_park.sum(axis=1) < 3).mean()

0.632

In [89]:
(food_truck_park.sum(axis=1) >= 4).mean()

0.13

In [195]:
n_days = 3

In [199]:
#0 = no trucks, 1 = truck show up
trucks = np.random.choice(([0,1]), size = (100_000,n_days), p = [0.3, 0.7])

In [200]:
trucks

array([[0, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       ...,
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [201]:
(trucks.sum(axis=1) == 0).mean()

0.02681

In [202]:
(trucks.sum(axis=1) >= 1).mean()

0.97319

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [216]:
n_trials = nrows = 1000
n_people = ncols = 23

birthdays = pd.DataFrame(np.random.choice((range(1,366)), n_trials * n_people))
birthdays

0
0      354
1      245
2      256
3      204
4       33
...    ...
22995  308
22996  249
22997  178
22998   16
22999   31

[23000 rows x 1 columns]

In [217]:
(birthdays.duplicated().mean())



0.9841304347826086

In [218]:
2/1000

0.002

In [219]:
birthdays.duplicated().nunique()

2

In [230]:
outcomes = range(1,366)
n_students = 40

In [231]:
birthdays = pd.DataFrame(np.random.choice(outcomes, size = (100_000,n_students)))

In [232]:
birthdays

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0      250   50  279   26   31  350   86  339  330  241  ...   38  274   86   
1       10  294  114  111   70  356   45   35  281  231  ...  364  350  113   
2       26  183  215   58  347  245  103  276   43   32  ...  297  197  332   
3      281  209  185  335   65  297  320  236  306  239  ...   72  295  205   
4       81   23   66  235    6  191  190  189  265  117  ...  265  108  317   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  180   57  138  116   86  191  276  258  249   94  ...  270  166  260   
99996  282   85  111  256  294  198  217  167  189   53  ...  209   39  223   
99997   75  145  215  161  238  233  248  246   79  280  ...   23  171  291   
99998  332  294  239  151  279   62   47   66  193   83  ...  154   54  128   
99999  350  249   22  228   44   98   27  124  110  357  ...  182  210  260   

        33   34   35   36   37   38   39  
0       20   81  255  222  136   65  239  
1       58  151  194  261  218  349  189  
2      289   14  202  116  365   60  361  
3      140  131  338   24  338  320  283  
4       85   45  362  311   21  287  248  
...    ...  ...  ...  ...  ...  ...  ...  
99995  234   75  354  166   60  158   23  
99996  111  212  346  306  207  216   91  
99997  309  273  122  355   80   90  209  
99998  184    7  130  304   66   75   37  
99999  266  332   31  265   11  328  171  

[100000 rows x 40 columns]

In [223]:
(birthdays.nunique(axis = 1) < 23).mean()

0.50325

In [229]:
(birthdays.nunique(axis = 1) < 20).mean()

0.41017

In [233]:
(birthdays.nunique(axis = 1) < 40).mean()

0.89261